import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript'; //https://www.npmjs.com/package/@rollup/plugin-typescript

const isProd = (process.env.BUILD === 'production');

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: 'src/main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'named', //Type:	"auto" | "default" | "named" | "none". Default "auto".
    banner,
  },
  external: ['obsidian'],// Keep Obsidian runtime APIs out of the bundle; they are provided by the host app.
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
  ]
};